security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

pkce:
  authorization-header: Basic dXNlcjpwYXNzd29yZA==
  client-id: 8eaf2f91-c9cb-4567-8cb6-84d874de48ab
  client-secret: my_super_secret_client_secret
  access-token-uri: https://my.idp/token
  user-authorization-uri: https://my.idp/authorize
  user-info-uri: https://my.idp/userinfo
  scope: openid+profile
  code-challenge-method: S256
  response-type: code+id_token
  cookie-name: bearer_token
  secure-cookie: true

server:
  port: 8888
